<a href="https://colab.research.google.com/github/Kaaviyaa-A/Assignment/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# # change tensorflow version to version 1.x
%tensorflow_version 1.x

import tensorflow
print(tensorflow.__version__)

TensorFlow 1.x selected.
1.15.2


In [2]:
import tensorflow as tf

# define x
x = tf.placeholder(dtype=tf.float32,shape=(2,3),name="x")

In [3]:
# declared y
# y is unknown(output)
y = tf.Variable(tf.zeros([2, 3],dtype=tf.float32))

In [4]:
# Equation -> (x + 1 / 2x^2 – 4)
# Evaluation
z=tf.subtract(tf.add(x,tf.math.multiply(tf.divide(1,2),tf.pow(x,2))),4)


In [5]:
learning_rate = 0.001
# Mean squared error
loss = tf.reduce_mean(tf.square(y-z))
# Optimizer(Adam)
train_op = tf.train.AdamOptimizer(learning_rate).minimize(loss)


In [6]:
#Create Object
saver = tf.train.Saver()

In [7]:
init = tf.global_variables_initializer()     # An Op that initializes global variables in the graph.

sess = tf.Session();                         # object encapsulates the environment in which Operation objects 
                                             # are executed, and Tensor objects are evaluated.
sess.run(tf.global_variables_initializer())

In [8]:
import numpy as np
rand_array = np.random.rand(2,3)     # Random Array
print(sess.run(z,feed_dict={x: rand_array}))


[[-3.9240339 -2.7297394 -2.6522446]
 [-2.9155002 -3.2535453 -3.6960154]]


In [9]:
saver.save(sess, 'equation')     # save the model as equation

'equation'

In [10]:
# Restore
sess = tf.Session()
new_saver = tf.train.import_meta_graph('equation.meta')
new_saver.restore(sess, tf.train.latest_checkpoint('./'))

INFO:tensorflow:Restoring parameters from ./equation


In [11]:
rand_array = np.random.rand(2,3)
print(rand_array)
print(sess.run(z,feed_dict={x: rand_array}))

[[0.47426543 0.65500655 0.12342953]
 [0.40485462 0.40736972 0.58355032]]
[[-3.4132707 -3.1304765 -3.868953 ]
 [-3.513192  -3.5096552 -3.2461843]]
